feat: create paymentPending component, setItem "paymentPending" in lo…
easytoliveapp/ez2live-app pull request #199
Opened 2024-08-07 13:46 UTC by femacedogomes

…calstorage, remove cancel free trial test buttons

2024-08-09 02:26 UTC, pedrohbl03 requested changes

2024-08-09 02:26 UTC, pedrohbl03 commented on src/components/mols/NavBarLogged/index.tsx
> +
O que isso faz???

```suggestion
  useEffect(() => {
    hasPaymentPending;
  }, [hasPaymentPending]);

```

2024-08-09 02:33 UTC, femacedogomes commented on src/components/mols/NavBarLogged/index.tsx
> +
fixed

2024-08-12 17:24 UTC, pedrohbl03 approved these changes

2024-08-12 17:24 UTC, merged